"""add users table and user_id

Revision ID: 1e3ff5376621
Revises: 99bb86b30d8a
Create Date: 2026-06-24 15:43:12.386060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3ff5376621'
down_revision: Union[str, None] = '99bb86b30d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('chat_history', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'])
    op.add_column('code_reviews', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'code_reviews', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'code_reviews', type_='foreignkey')
    op.drop_column('code_reviews', 'user_id')
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_column('chat_history', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
