"""initial schema

Revision ID: 99bb86b30d8a
Revises: 
Create Date: 2026-06-24 15:19:16.484621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99bb86b30d8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_history_session_time', table_name='chat_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_history_session_time', 'chat_history', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
